Day 3 Assignment 

In [2]:
import numpy as np

arr = np.arange(2,50,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [20]:
#Question2

def createList(l):
  print("Enter 5 elements")
  for j in range(5):
    ele = input()
    l.append(ele)
  print("Finished creating the list")

list1=[]
list2=[]
createList(list1)
createList(list2)
print(list1)
print(list2)

arr1 = np.array(list1)
arr2 = np.array(list2)

concatArr = np.concatenate((arr1,arr2),axis=None)
print(concatArr)

srt1 = np.sort(arr1)
print(srt1)
srt2 = np.sort(arr2)
print(srt2);

Enter 5 elements
jack
Jill
merlin
78
33
Finished creating the list
Enter 5 elements
34
56
345948
Old
tenet
Finished creating the list
['jack', 'Jill', 'merlin', '78', '33']
['34', '56', '345948', 'Old', 'tenet']
['jack' 'Jill' 'merlin' '78' '33' '34' '56' '345948' 'Old' 'tenet']
['33' '78' 'Jill' 'jack' 'merlin']
['34' '345948' '56' 'Old' 'tenet']


In [26]:
#Question3

arr = np.array([[[1,2,3],[4,5,6],[7,89,92]],[[3,4,5],[1,1,1],[0,9,0]]])

print("Size of the ndarray",arr.size)
print("Dimensions of the ndarray",arr.ndim)


Size of the ndarray 18
Dimensions of the ndarray 3


In [44]:
#Question 4

arr = np.ones(3)

arr_2d = arr[np.newaxis]

print(arr_2d.ndim)
print(arr_2d)

#expand_dims()

NewArr_2d = np.expand_dims(arr, axis = 0) 

print(NewArr_2d)
print(NewArr_2d.ndim)

vert_arr = np.expand_dims(arr,axis = 1)

print(vert_arr)
print(vert_arr.ndim)

2
[[1. 1. 1.]]
[[1. 1. 1.]]
2
[[1.]
 [1.]
 [1.]]
2


In [50]:
#Question 5

arr1 = np.ones((10,10))
print(arr1, end="\n\n")

arr2 = np.identity(10)
print(arr2,end="\n\n")

print("Horizontal Stack : \n", np.hstack((arr1,arr2)),end="\n\n")

print("Vertical Stack : \n ", np.vstack((arr1,arr2)),end="\n\n")


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

Horizontal Stack : 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [57]:
#Question 6

arr5 = np.random.randint(2,100,(3,6))
print(arr5, end="\n\n")

print("Unique elements with count: \n", np.unique(arr5,return_counts=True))


[[50 43 33 57 14 11]
 [75 25 44 80 15 28]
 [97 25 24 90 30 81]]

Unique elements with count: 
 (array([11, 14, 15, 24, 25, 28, 30, 33, 43, 44, 50, 57, 75, 80, 81, 90, 97]), array([1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))
